# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('wheight', models.FloatField()),
                ('condition_1', models.CharField(max_length=30, null=True)),
                ('condition_2', models.CharField(max_length=30, null=True)),
                ('condition_3', models.CharField(max_length=30, null=True)),
                ('observations', models.CharField(max_length=255, null=True)),
                ('modified_By', models.PositiveIntegerField()),
                ('modified_DT', models.DateField()),
            ],
        ),
    ]
