# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=30)),
                ('created_dt', models.DateField()),
                ('created_tm', models.TimeField()),
                ('received_Place', models.CharField(default='Cuarto', max_length=30)),
                ('received_State', models.CharField(default='Despierto', max_length=30)),
                ('service_Food', models.CharField(default='Desayuno', max_length=30)),
                ('returned_Type', models.CharField(default='Cuarto', max_length=30)),
                ('diaper', models.CharField(max_length=10, null=True)),
                ('evacuations', models.CharField(max_length=10, null=True)),
                ('milk', models.CharField(max_length=10, null=True)),
                ('snack', models.CharField(max_length=10, null=True)),
                ('hygiene', models.CharField(max_length=10, null=True)),
                ('comments', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
