# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='observations',
            new_name='more_info',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='wheight',
            new_name='weight',
        ),
    ]
