# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='address2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_last_name',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='mid_name',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='second_last_name',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='zipcode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
