# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 13:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=30)),
                ('created_dt', models.DateField(auto_now_add=True)),
                ('created_tm', models.TimeField(auto_now_add=True)),
                ('received_Place', models.CharField(blank=True, choices=[('Cuarto', 'Cuarto'), ('Sala', 'Sala'), ('Comedor', 'Comedor'), ('Area de Juegos', 'Area de Juegos')], max_length=30, null=True)),
                ('received_State', models.CharField(blank=True, choices=[('Dormido', 'Dormido'), ('Despierto', 'Despierto')], max_length=30, null=True)),
                ('service_Food', models.CharField(blank=True, choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena')], max_length=30, null=True)),
                ('returned_Type', models.CharField(blank=True, choices=[('Cuarto', 'Cuarto'), ('Sala', 'Sala'), ('Comedor', 'Comedor'), ('Area de Juegos', 'Area de Juegos')], max_length=30, null=True)),
                ('diaper', models.CharField(blank=True, choices=[('0', '0'), ('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6')], max_length=10, null=True)),
                ('evacuations', models.CharField(blank=True, choices=[('0', '0'), ('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6')], max_length=10, null=True)),
                ('milk', models.CharField(blank=True, choices=[('0', '0'), ('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6')], max_length=10, null=True)),
                ('snack', models.CharField(blank=True, choices=[('0', '0'), ('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6')], max_length=10, null=True)),
                ('hygiene', models.CharField(blank=True, choices=[('0', '0'), ('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6')], max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('mid_name', models.CharField(blank=True, max_length=1, null=True)),
                ('first_last_name', models.CharField(default='', max_length=30)),
                ('second_last_name', models.CharField(default='', max_length=30)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_plan_name', models.CharField(blank=True, max_length=30, null=True)),
                ('medical_plan_number', models.CharField(blank=True, max_length=30, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('condition_1', models.CharField(blank=True, max_length=30, null=True)),
                ('condition_2', models.CharField(blank=True, max_length=30, null=True)),
                ('condition_3', models.CharField(blank=True, max_length=30, null=True)),
                ('more_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_DT', models.DateField(blank=True, default=datetime.date(2016, 5, 20), null=True)),
                ('modified_DT', models.DateField(blank=True, null=True)),
                ('created_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('modified_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Record'),
        ),
    ]
