# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=30)),
                ('mid_name', models.CharField(max_length=1)),
                ('first_last_name', models.CharField(default='unknown', max_length=30)),
                ('second_last_name', models.CharField(default='unknown', max_length=30)),
                ('birthdate', models.DateField(auto_now_add=True)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('height', models.FloatField()),
                ('wheight', models.FloatField()),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.PositiveIntegerField()),
                ('doctor', models.ManyToManyField(to='doctor.Doctor')),
            ],
        ),
    ]
