# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.Treatment')),
            ],
        ),
    ]
