# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 20:04
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='America/Puerto_Rico'),
        ),
    ]
