# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='treatment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
