# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20160301_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
